---
title: "Acerca de mí"
---

## Educación

Soy Licenciada en Sistemas de Información(UNNE) y Diplomada en Ciencias de Datos, Aprendizaje Automático y sus Aplicaciones por la FAMAF de la Universidad Nacional de Córdoba. Actualemente, estoy cursando una maestría en Tecnologías de la Información en UNNE.

## Experiencia

Gobierno: Trabajo desarrollando soluciones digitales con Genexus y Sql en una entidad de gobierno de la Prov. del Chaco., donde algunas de mis funciones son relevar las necesidades de los usuarios, diseñar y desarrollas un sistema que satisfaga las necesidades relevadas y redactar documentación técnica. También capacito a los nuevos integrantes para que puedan aportar valor al equipo.

Organización sin fines de Lucro: Desde el 2021 hasta principios del 2025, formé parte activa del equipo de accesibilidad en Metadocencia, donde trabajamos incansablemente para promover una educación inclusiva y accesible para todos. En el 2023 me incorporé al equipo de Comunidad, donde trabajé en el proyecto [mapeo de comunidades, eventos y recursos de ciencia abierta](https://ciencia-abierta-en-latinoamerica.netlify.app/), partir del 2024 dicté el módulo de Código Abierto de las cohortes de formación virtual ALTaCA (América Latina Transforma a la Ciencia Abierta). Actualmente, soy parte del parte Polen.

Mis credenciales reflejan mi compromiso con la educación y el empoderamiento a través de la tecnología e incluyen la certificación como:

-   [Instructora por The Carpentries](https://carpentries.org/instructors/),

-   [Instructora de tidyverse por Rstudio](https://education.rstudio.com/trainers/),

-   [Fundamentos de Construcción de comunidades científicas](https://badgr.com/public/assertions/ogcwi_Y8RZWedkV70_oiPQ?identity__email=patricialoto@metadocencia.org).

## Comunidades

Participo activamente de distintas comunidades promoviendo la accesibilidad y la enseñanza de R, tales como R-Ladies, [Latin-R](https://latin-r.com/sobre/equipo/) y [The Turing Way](https://the-turing-way.netlify.app/index.html). También colaboré con OLS, primero participé como mentee de la [cohorte nro. 7](https://openlifesci.org/openseeds/ols-7/projects-participants.html) del Programa de mentoreo y entrenamiento Open Seeds dictado por la increíble comunidad [Open Life Science (OLS)](https://openlifesci.org/). Esta experiencia fue fundamental ya que me proporciono conocimientos sólidos y experiencias valiosas sobre gestión de proyectos, trabajo colaborativo, datos y licencias abiertas y construcción de comunidades de prácticas. Finalmente, fui mentora del proyecto [PsychGIGA](https://github.com/vskentrou/PsychGIGA/issues/3) en la cohorte nro. 8 (OLS-8), donde colaboré y apoyé a los mentees en diferente acivitidades (como la definición de una hoja de ruta, la elaboración de un canvas del proyecto, los conecté con expertos en temas de licenciamiento, entre otras), como así también los guíe en la toma de decisiones.

## Proyectos

Actuales:

-   [Asistente Virtual como apoyo a la implementación de prácticas de Ciencia Abierta en Latinoamérica](https://github.com/PatriLoto/asistente_virtual_CA)

-   [Template para elaborar un plan de gestión de software](https://github.com/PatriLoto/PGSoftware)

Proyectos anteriores :

-   [Mapeo de Comunidades](https://www.metadocencia.org/proyecto/mapeo-comunidades/)

-   [ALTa Ciencia Abierta](https://www.metadocencia.org/alta-ca/2-2024/)

-   [Determining Climate Risks with NASA Earthdata Cloud](https://github.com/ScienceCore/climaterisk)
